name: mplsoccer-docs
channels:
  - anaconda
  - conda-forge
dependencies:
  - pandas
  - scipy
  - seaborn
  - sphinx
  - cmasher
  - pyarrow
  - beautifulsoup4
  - lxml
  - pillow
  - pip
  - sphinx-gallery
  - sphinx_rtd_theme
  - numpydoc
  - pip:
      - -e .
      - highlight-text
      - kloppy
