name: mplsoccer
channels:
  - anaconda
  - conda-forge
dependencies:
  - jupyter
  - pandas
  - scipy
  - cmasher
  - seaborn
  - beautifulsoup4
  - pyarrow
  - pillow
  - lxml
  - pip
  - pip:
      - mplsoccer
      - highlight-text
